import NavBar from './components/navbar/NavBar'
import Modal from './components/modals/Modal'
import RegisterModal from './components/modals/RegisterModal'
import ToasterProvider from './providers/ToasterProvider'
import LoginModal from './components/modals/LoginModal'
import getCurrentUser from './actions/getCurrentUser'
import RentModal from './components/modals/RentModal'
import './globals.css'

export const metadata = {
  title: 'ACE',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
 const currentUser = await getCurrentUser();

  return (
    <html lang="en">
      <body >
          <ToasterProvider />
          <LoginModal />
          <RegisterModal />
          <RentModal />
          <NavBar currentUser={currentUser} />
        <div className="pb-20 pt-28">
          {children}
        </div>
      </body>
    </html>
  )
}
